version: '2.1'

services:
  golang:
    build:
      context: .
      dockerfile: .docker/golang/Dockerfile
    ports:
      - 5002:5002
    links:
      - fluentd
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        fluentd-async-connect: 'true'
#        fluentd-retry-wait: '5s'
#        fluentd-max-retries: '30'
#        tag: simblebank.gateway

  web:
    image: httpd
    ports:
      - "8082:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  kibana:
    image: kibana:6.8.3
    ports:
      - 5601:5601
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:6.8.3
    expose:
      - 9200
    ports:
      - 9200:9200

  fluentd:
    build: .docker/fluentd
    links:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp
